# Generated by Django 5.2.5 on 2026-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0002_documenttype_pickupslot_strand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerequest',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='filerequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
