# Generated by Django 6.0 on 2026-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0002_filerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
