# Generated by Django 5.2.5 on 2026-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0002_filerequest_pass_key_filerequest_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='no_accountabilities',
            field=models.BooleanField(default=False),
        ),
    ]
