# Generated by Django 6.0 on 2026-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0003_alter_staff_full_name_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filerequest',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
