# Generated by Django 5.2.5 on 2026-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0003_filerequest_no_accountabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_slots', models.IntegerField(default=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
