# Generated by Django 5.2.5 on 2026-02-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0006_studentdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerequest',
            name='pass_key',
        ),
    ]
