# Generated by Django 5.2.5 on 2026-02-27 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0008_strand_alter_filerequest_strand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='processed_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_documents', to='request_backend.filerequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
