# Generated by Django 5.2.5 on 2026-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0009_processeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='passkey',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
