# Generated by Django 5.2.5 on 2026-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0010_filerequest_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerequest',
            name='passkey',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
