# Generated by Django 5.2.5 on 2026-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0013_studentmasterdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupslot',
            name='max_slots',
        ),
        migrations.AddField(
            model_name='pickupslot',
            name='afternoon_slots',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pickupslot',
            name='morning_slots',
            field=models.IntegerField(default=10),
        ),
    ]
