# Generated by Django 5.2.5 on 2026-03-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0015_filerequest_request_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
