# Generated by Django 5.2.5 on 2026-03-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0014_remove_pickupslot_max_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
