# Generated by Django 5.2.5 on 2026-03-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0016_alter_staff_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerequest',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
    ]
